branches:
  only:
    - master
notifications:
  email: false

language: c++
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-4.8

env:
  - COMPILER=g++-5
  - COMPILER=g++-4.8

before_install:
  - MINICONDA=Miniconda-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - echo $PATH
  - which python && python --version
  - conda install --yes -c r nlopt
  - conda install --yes boost
  - echo 'Y' | conda install --yes -c psi4 psi4

install:
  - ./configure --cxx=$COMPILER --with-nlopt=$HOME/miniconda/lib/
  - make

script:
  - ldd resp2.so
  - psi4 input.dat
  - cat output.dat
