branches:
  only:
    - master
notifications:
  email: false

language: c++
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-4.8

env:
  - COMPILER=g++-5
  - COMPILER=g++-5

before_install:
  - wget --quiet http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xzf nlopt-2.4.2.tar.gz
  - (cd nlopt-2.4.2 &&
     CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --prefix=$HOME/usr &&
     make &&
     make install)

  - MINICONDA=Miniconda-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - echo $PATH
  - which python && python --version
  - conda install --yes boost
  - echo 'Y' | conda install --yes -c psi4 psi4

install:
  - ./configure --cxx=$COMPILER --with-nlopt=$HOME/usr
  - make

script:
  - ldd resp2.so
  - psi4 input.dat
  - cat output.dat
