language: c++
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-4.8
      - libnlopt-dev

env:
  - CXX=g++-5
  - CXX=g++-4.8

branches:
  only:
    - master

before_install:
  - MINICONDA=Miniconda-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - echo $PATH
  - which python && python --version
  - echo 'Y' | conda install --yes -c psi4 psi4

install:
  - ./configure --cxx=$CXX
  - cat Makefile
  - make

script:
  - psi4
